# Generated by Django 2.0.3 on 2018-08-29 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PZ', 'Pizza'), ('SB', 'Subs'), ('PA', 'Pasta'), ('SA', 'Salad'), ('DP', 'Dinner Platters')], max_length=2)),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('valid_for', models.CharField(choices=[('P', 'Pizza Only'), ('S', 'Subs Only'), ('B', 'Both Pizza and Subs')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.MenuItem')),
                ('crust', models.CharField(choices=[('S', 'Sicilian'), ('R', 'Regular')], max_length=1)),
                ('size', models.CharField(choices=[('S', 'Small'), ('R', 'Regular')], max_length=1)),
                ('number_of_toppings', models.SmallIntegerField(choices=[(0, 'Cheese only'), (1, '1 topping'), (2, '2 toppings'), (3, '3 toppings'), (5, 'Special')])),
            ],
            bases=('orders.menuitem',),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='orders.Topping'),
        ),
    ]
