# Generated by Django 2.0.3 on 2018-08-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180829_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('L', 'Large'), ('', '')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='number_of_toppings',
            field=models.SmallIntegerField(choices=[(0, 'No extra toppings'), (1, '1 topping'), (2, '2 toppings'), (3, '3 toppings'), (5, 'Special')]),
        ),
    ]
