# Generated by Django 2.0.3 on 2018-08-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20180829_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='number_of_toppings',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='number_of_toppings',
            field=models.SmallIntegerField(choices=[(0, 'No extra toppings'), (1, '1 topping'), (2, '2 toppings'), (3, '3 toppings'), (5, 'Special')], default=0),
        ),
        migrations.AlterField(
            model_name='topping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.002, max_digits=3),
        ),
    ]
