# Generated by Django 2.0.3 on 2018-08-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180830_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='options',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
    ]
