# Generated by Django 2.0.3 on 2018-08-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_menuitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='crust',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='crust',
            field=models.CharField(choices=[('S', 'Sicilian'), ('R', 'Regular'), ('', '')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='pizza',
            name='name2',
            field=models.CharField(default='', max_length=1),
        ),
    ]
