# Generated by Django 2.0.3 on 2018-08-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20180830_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='menuitem_ptr',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
