# Generated by Django 2.0.3 on 2018-08-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20180830_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='options',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('C', 'Cheese-only')], default='N', max_length=1),
        ),
    ]
