# Generated by Django 2.0.3 on 2018-08-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180830_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='crust',
            field=models.CharField(choices=[('S', 'Sicilian'), ('R', 'Regular'), ('NA', 'N/A')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('L', 'Large'), ('NA', 'N/A')], max_length=1),
        ),
    ]
