# Generated by Django 2.0.3 on 2018-08-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20180830_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(editable=False),
        ),
    ]
