# Generated by Django 2.0.3 on 2018-08-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20180831_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
