# Generated by Django 2.0.3 on 2018-09-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20180901_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
