# Generated by Django 2.0.3 on 2018-09-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20180902_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='toppings',
        ),
    ]
