# Generated by Django 2.0.3 on 2018-09-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_orderlines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('type', 'name', 'size', 'number_of_toppings')},
        ),
        migrations.AddField(
            model_name='orderlines',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
