# Generated by Django 2.0.3 on 2018-09-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('order_on_menu',)},
        ),
        migrations.AddField(
            model_name='type',
            name='order_on_menu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Type'),
        ),
    ]
