# Generated by Django 2.0.3 on 2018-09-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20180903_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='type_new',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.Type'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.CharField(choices=[('PZ', 'Pizza'), ('SB', 'Subs'), ('PA', 'Pasta'), ('SA', 'Salad'), ('DP', 'Dinner Platters')], max_length=2),
        ),
    ]
