# Generated by Django 2.0.3 on 2018-09-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20180903_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('type_new', 'name', 'size', 'number_of_toppings')},
        ),
    ]
