# Generated by Django 2.0.3 on 2018-09-03 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20180903_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('type', 'name', 'size', 'number_of_toppings')},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='type_new',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.Type'),
        ),
    ]
