# Generated by Django 2.0.3 on 2018-09-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20180903_1422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('type_new', 'name', 'size', 'number_of_toppings')},
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='type',
            new_name='type_new',
        ),
    ]
