# Generated by Django 2.0.3 on 2018-09-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_remove_menuitem_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='type',
        ),
    ]
