# Generated by Django 2.0.3 on 2018-09-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_remove_type_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='image_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
